Fix error message being printed to wrong output.
This can both cause and hide problems, because the Mender client will
attempt to parse it, and it won't be visible in logs.

Changelog: Commit

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

diff --git a/fw_printenv b/fw_printenv
--- a/fw_printenv
+++ b/fw_printenv
@@ -48,7 +48,7 @@ fi
 
 # If empty, something is wrong and no point in proceeding
 if [ -z "${GRUB_EDITENV}" ]; then
-    echo "Could not find a valid grub-editenv binary. Aborting..."
+    echo "Could not find a valid grub-editenv binary. Aborting..." 1>&2
     exit 1
 fi
 
